# Generated by Django 5.2.6 on 2026-01-08 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_alter_cartfood_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuID', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.category')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.food')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='api.restaurant')),
            ],
            options={
                'db_table': 'tbl_menu',
                'ordering': ['category', 'food__foodName'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('statusID', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Хүлээгдэж буй'), ('approved', 'Батлагдсан'), ('preparing', 'Бэлтгэж байна'), ('ready', 'Бэлэн'), ('delivered', 'Хүргэгдсэн'), ('cancelled', 'Цуцлагдсан')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='api.order')),
            ],
            options={
                'db_table': 'tbl_order_status',
                'ordering': ['-created_at'],
            },
        ),
    ]
