# Generated by Django 5.2.6 on 2026-01-08 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cartfood_id'),
        ('restaurant_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('min_stock_level', models.IntegerField(default=10)),
                ('unit', models.CharField(default='ш', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='api.food')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='api.restaurant')),
            ],
            options={
                'db_table': 'tbl_inventory',
                'unique_together': {('food', 'restaurant')},
            },
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('monday', 'Даваа'), ('tuesday', 'Мягмар'), ('wednesday', 'Лхагва'), ('thursday', 'Пүрэв'), ('friday', 'Баасан'), ('saturday', 'Бямба'), ('sunday', 'Ням')], max_length=20)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='api.restaurant')),
            ],
            options={
                'db_table': 'tbl_operating_hours',
                'ordering': ['day_of_week'],
                'unique_together': {('restaurant', 'day_of_week')},
            },
        ),
    ]
