# Generated by Django 6.0.1 on 2026-01-08 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catID', models.BigAutoField(primary_key=True, serialize=False)),
                ('catName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_category',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('percent', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbl_coupon',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPrice',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('map', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_deliveryPrice',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_order',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('resID', models.BigAutoField(primary_key=True, serialize=False)),
                ('resName', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_restaurant',
            },
        ),
        migrations.CreateModel(
            name='RestaurantType',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_restaurantType',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.BigAutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('workerID', models.BigAutoField(primary_key=True, serialize=False)),
                ('workerName', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_worker',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodID', models.BigAutoField(primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=255)),
                ('catID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('resID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
            ],
            options={
                'db_table': 'tbl_food',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
            options={
                'db_table': 'tbl_history',
            },
        ),
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('foodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.food')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
            options={
                'db_table': 'tbl_orderFood',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payID', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('turul', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
            options={
                'db_table': 'tbl_payment',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restauranttype'),
        ),
        migrations.AddField(
            model_name='order',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'tbl_notification',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commID', models.BigAutoField(primary_key=True, serialize=False)),
                ('review', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('foodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.food')),
                ('resID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'tbl_comment',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartID', models.BigAutoField(primary_key=True, serialize=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'tbl_cart',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('detail_address', models.CharField(max_length=255)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'tbl_address',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('payID', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('workerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.worker')),
            ],
            options={
                'db_table': 'tbl_delivery',
            },
        ),
        migrations.CreateModel(
            name='CartFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('cartID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cart')),
                ('foodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.food')),
            ],
            options={
                'db_table': 'tbl_cartFood',
                'unique_together': {('cartID', 'foodID')},
            },
        ),
    ]
